"""Constants for Elten adapter."""

# CSV column indices (0-based)
# These map to the column order in the Elten CSV file
CSV_COLUMN_MAPPING = {
    "LIEFERANTEN_ILN": 0,
    "LIEFERANTEN_NAME": 1,
    "HERSTELLER_ARTIKELEAN": 2,
    "HERSTELLER_ARTIKELNR_INDEX": 3,
    "HERSTELLER_ARTIKELNR": 4,
    "HERSTELLER_ARTIKELGROESSE": 5,
    "HERSTELLER_ARTIKELSORTIMENT": 6,
    "HERSTELLER_ARTIKELNAME": 7,
    "HERSTELLER_ARTIKELBEZEICHNUNG1": 8,
    "HERSTELLER_ARTIKELBEZEICHNUNG2": 9,
    "HERSTELLER_ARTIKELGRUPPE": 10,
    "GUELTIG_AB": 11,
    "WAEHRUNG": 12,
    "MWST_INLAND": 13,
    "LISTENPREIS": 14,
    "PREISEINHEIT": 15,
    "ZOLLTARIFNR": 16,
    "URSPRUNGSLAND": 17,
    "URSPRUNGSLAND-ISO-3166-A2": 18,
    "ECLASS": 19,
    "ECLASS_VERSION": 20,
    "GEWICHTPROME": 21,
    "BEZUGS_ME": 22,
    "INHALT_ME": 23,
    "INHALT_MENGE": 24,
    "A01_OBERMATERIAL": 25,
    "A02_FUTTERMATERIAL": 26,
    "A03_LASCHE": 27,
    "A04_EINLEGESOHLE": 28,
    "A05_BRANDSOHLE": 29,
    "A06_DURCHTRITTSCHUTZ": 30,
    "A07_SOHLE": 31,
    "A08_SPITZENSCHUTZ": 32,
    "A10_ZEHENSCHUTZKAPPE": 33,
    "A09_NORM": 34,
    "A11_ZUSATZINFO1": 35,
    "A12_ZUSATZINFO2": 36,
    "A13_SONSTIGES1": 37,
    "A14_SONSTIGES2": 38,
    "MEDIA": 39,
}

# Default values
DEFAULT_CURRENCY = "EUR"
DEFAULT_PACKAGE = "kartonnen doos"
META_DESCRIPTION_MAX_LENGTH = 317
